source 'https://rubygems.org'

gem 'rails', '3.2.22.1'

gem 'react_webpack_rails', path: '../..'
gem 'sqlite3'
gem 'active_model_serializers'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
end

group :test do
  gem 'rspec-rails'
  gem 'test-unit', '~> 3.0'
  gem 'capybara'
  gem 'selenium-webdriver'
end
